import { useState, type FormEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useQueryClient } from '@tanstack/react-query';
import { send } from '../api';
import { useProject } from '../App';
import { Empty, ErrorMessage, Header, Json, Loading, Status, Table, time, useResource } from '../components/ui';
type Question={id:string;label:string;type:string;options?:string[];min?:number;max?:number};
type Item={id:string;status:string;revision:number;answers:Record<string,unknown>;content:Record<string,unknown>};
type Queue={id:string;name:string;questions:Question[];items:Item[];created_at:string};
export default function Reviews(){const{id}=useParams();return id?<ReviewDetail id={id}/>:<ReviewList/>}
function ReviewList(){const{project,base}=useProject();const result=useResource<Queue[]>(`/projects/${project.id}/reviews`);return <><Header title="Review queues" subtitle="Turn expert judgment into attributed, inspectable feedback."/><ErrorMessage error={result.error}/>{result.isPending?<Loading/>:result.data?.length?<Table headers={['Queue','Questions','Created']}>{result.data.map(q=><tr key={q.id}><td><Link to={`${base}/reviews/${q.id}`}>{q.name}</Link></td><td>{q.questions.length}</td><td>{time(q.created_at)}</td></tr>)}</Table>:<Empty title="No review queues yet"><p>Select cases in an evaluation and create a review queue.</p><Link to={`${base}/evaluations`}>Open evaluations →</Link></Empty>}</>}
function ReviewDetail({id}:{id:string}){const{base}=useProject();const result=useResource<Queue>(`/reviews/${id}`,true);const[index,setIndex]=useState(0);const[error,setError]=useState<unknown>();const cache=useQueryClient();if(result.isPending)return <Loading/>;if(!result.data)return <ErrorMessage error={result.error}/>;const queue=result.data;const items=queue.items.filter(i=>i.status==='pending');const item=items[index]||items[0];async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const answers:Record<string,unknown>={};for(const q of queue.questions){const v=d.get(q.id);answers[q.id]=q.type==='pass_fail'?v==='true':q.type==='numeric'?Number(v):q.type==='multi_category'?d.getAll(q.id):v}try{await send(`/review-items/${item.id}/submit`,{revision:item.revision,answers});cache.invalidateQueries();setError(null)}catch(e){setError(e);cache.invalidateQueries()}}return <><Link className="breadcrumb" to={`${base}/reviews`}>Review queues /</Link><Header title={queue.name} subtitle={`${queue.items.length-items.length} of ${queue.items.length} reviewed`}/><ErrorMessage error={error}/>{item?<div className="review-layout"><section><h2>Input & context</h2><Json value={item.content.input}/><h2>Response</h2><Json value={item.content.output}/>{item.content.expected!==undefined&&<><h2>Expected</h2><Json value={item.content.expected}/></>}</section><form key={item.id} onSubmit={submit}><h2>Your assessment</h2>{queue.questions.map(q=><label key={q.id}>{q.label}{q.type==='pass_fail'?<select name={q.id} required><option value="">Choose…</option><option value="true">Pass</option><option value="false">Fail</option></select>:q.type==='numeric'?<input type="number" name={q.id} min={q.min??0} max={q.max??5} required/>:q.type==='category'?<select name={q.id} required>{q.options?.map(v=><option key={v}>{v}</option>)}</select>:q.type==='multi_category'?<select name={q.id} multiple required>{q.options?.map(v=><option key={v}>{v}</option>)}</select>:<textarea name={q.id} rows={4} required={q.type==='expected_answer'}/>}</label>)}<div className="actions"><button>Submit review</button><button type="button" className="quiet" onClick={async()=>{try{await send(`/review-items/${item.id}/submit`,{revision:item.revision,answers:{},decline:true});cache.invalidateQueries()}catch(e){setError(e)}}}>Decline</button><button type="button" className="quiet" disabled={items.length<2} onClick={()=>setIndex((index+1)%items.length)}>Next item →</button></div><small>Your submission is attributed and protected against concurrent overwrites.</small></form></div>:<Empty title="Queue complete"><p>All items have been reviewed or declined. Answers remain available through the API.</p></Empty>}</>}
