import { useState, type FormEvent } from 'react';
import { NavLink, Route, Routes } from 'react-router-dom';
import { useQueryClient } from '@tanstack/react-query';
import { send } from '../api';
import { useProject } from '../App';
import { Code, CopyButton, Dialog, ErrorMessage, Header, Json, Status, Table, time, useResource } from '../components/ui';
type Key={id:string;name:string;prefix:string;scopes:string[];expires_at:string;revoked_at:string|null};
export default function Settings(){const{base}=useProject();return <><Header title="Settings" subtitle="Access, credentials and project policy."/><nav className="tabs">{['general','keys','members','activity','privacy'].map(t=><NavLink key={t} to={`${base}/settings/${t}`}>{t}</NavLink>)}</nav><Routes><Route path="keys" element={<Keys/>}/><Route path="members" element={<Members/>}/><Route path="activity" element={<Activity/>}/><Route path="privacy" element={<Privacy/>}/><Route path="*" element={<General/>}/></Routes></>}
function General(){const{project}=useProject();return <section className="settings-panel"><h2>{project.name}</h2><p>{project.description}</p><label>Project ID<div className="copy-row"><code>{project.id}</code><CopyButton value={project.id}/></div></label><Code>{`pip install -e packages/sdk-python\n# Set these variables in your shell:\nFLUXRUN_URL=http://localhost:8000\nFLUXRUN_PROJECT=${project.id}\nFLUXRUN_API_KEY=<create a scoped key>`}</Code></section>}
function Keys(){const{project}=useProject();const result=useResource<Key[]>(`/projects/${project.id}/keys`);const[error,setError]=useState<unknown>();const[secret,setSecret]=useState('');const[open,setOpen]=useState(false);const cache=useQueryClient();async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);try{const r=await send<{secret:string}>(`/projects/${project.id}/keys`,{name:d.get('name'),scopes:d.getAll('scope'),expires_days:Number(d.get('days'))});setSecret(r.secret);setOpen(false);cache.invalidateQueries()}catch(e){setError(e)}}return <><div className="section-title"><div><h2>API keys</h2><p className="muted">Keys are scoped to this project. Secrets are shown once.</p></div><button onClick={()=>setOpen(true)}>Create key</button></div><ErrorMessage error={error||result.error}/><Table headers={['Name','Prefix','Scopes','Expires','Actions']}>{result.data?.map(k=><tr key={k.id}><td>{k.name}</td><td className="mono">{k.prefix}…</td><td>{k.scopes.join(', ')}</td><td>{time(k.expires_at)}</td><td>{k.revoked_at?<Status value="revoked"/>:<button className="quiet danger small" onClick={async()=>{if(!confirm(`Revoke ${k.name}? Scripts using it will lose access.`))return;try{await send(`/projects/${project.id}/keys/${k.id}/revoke`);cache.invalidateQueries()}catch(e){setError(e)}}}>Revoke</button>}</td></tr>)}</Table><Dialog title="Create API key" open={open} onClose={()=>setOpen(false)}><form onSubmit={create}><label>Name<input name="name" minLength={2} required/></label><label>Expires after (days)<input name="days" type="number" min={1} max={365} defaultValue={90}/></label><fieldset><legend>Permissions</legend>{['tracking:read','tracking:write','artifacts:write','registry:write','traces:write'].map(scope=><label className="check" key={scope}><input type="checkbox" name="scope" value={scope} defaultChecked/>{scope}</label>)}</fieldset><ErrorMessage error={error}/><button>Create key</button></form></Dialog><Dialog title="Copy your new API key" open={!!secret} onClose={()=>setSecret('')}><p>This secret cannot be retrieved again. Store it securely.</p><Code>{secret}</Code><button onClick={()=>setSecret('')}>I have saved the key</button></Dialog></>}
function Members(){const{workspace}=useProject();const result=useResource<{id:string;email:string;name:string;role:string}[]>(`/workspaces/${workspace.id}/members`);const[error,setError]=useState<unknown>();const cache=useQueryClient();async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const d=new FormData(form);try{await send(`/workspaces/${workspace.id}/members`,{email:d.get('email'),role:d.get('role')});form.reset();cache.invalidateQueries()}catch(e){setError(e)}}return <><h2>Workspace members</h2><ErrorMessage error={error||result.error}/><Table headers={['Name','Email','Role']}>{result.data?.map(m=><tr key={m.id}><td>{m.name}</td><td>{m.email}</td><td>{m.role}</td></tr>)}</Table>{['owner','admin'].includes(workspace.role)&&<form className="settings-panel" onSubmit={submit}><h3>Add or update a registered member</h3><label>Email<input name="email" type="email" required/></label><label>Role<select name="role">{['viewer','reviewer','editor','admin'].map(r=><option key={r}>{r}</option>)}</select></label><button>Save membership</button></form>}</>}
export function Activity(){const{workspace}=useProject();const result=useResource<{id:string;action:string;resource_type:string;resource_id:string;created_at:string;detail:unknown}[]>(`/workspaces/${workspace.id}/activity`,true);return <><h2>Workspace activity</h2><ErrorMessage error={result.error}/><Table headers={['Event','Resource','When','Details']}>{result.data?.map(e=><tr key={e.id}><td>{e.action}</td><td className="mono">{e.resource_type} / {e.resource_id.slice(-12)}</td><td>{time(e.created_at)}</td><td className="mono">{JSON.stringify(e.detail)}</td></tr>)}</Table></>}
function Privacy(){const{project}=useProject();const[error,setError]=useState<unknown>();const[saved,setSaved]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);try{await send(`/projects/${project.id}/privacy`,{store_trace_content:d.get('content')==='on',trace_retention_days:Number(d.get('days')),trace_preview_chars:Number(d.get('chars'))},'PATCH');setSaved(true)}catch(e){setError(e)}}return <form className="settings-panel" onSubmit={submit}><h2>Trace privacy & retention</h2><label className="check"><input name="content" type="checkbox" defaultChecked={project.settings.store_trace_content!==false}/>Store redacted input/output previews</label><label>Preview character limit<input name="chars" type="number" min={0} max={16000} defaultValue={Number(project.settings.trace_preview_chars??2000)}/></label><label>Retention (days)<input name="days" type="number" min={1} max={3650} defaultValue={Number(project.settings.trace_retention_days??30)}/></label><p className="muted">Secret keys are redacted before storage. Metadata-only mode applies to newly ingested traces.</p><ErrorMessage error={error}/>{saved&&<p role="status">Privacy settings saved.</p>}<button>Save privacy settings</button></form>}
